---

- hosts: amalie, thunderbug, bolt
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - name: Enable Redirector Traffic for {{inventory_hostname}}
      shell: /opt/enable-traffic-forwarding-rules-{{inventory_hostname}}.sh
