---

- hosts: localhost
  gather_facts: False
  roles:
    - role: github
    - role: dns

- hosts: support_lin
  gather_facts: True
  roles:
    - role: support_lintools
  vars:
    dns_servers: 
    - nameserver 91.52.201.22
    - nameserver 8.8.8.8

- hosts: stamp
  gather_facts: False
  roles:
    - role: mail
      
- hosts: nato-int.com 
  gather_facts: False
  roles:
    - role: web 

- hosts: amalie, thunderbug, bolt 
  gather_facts: False
  roles:
    - role: redirectors 
