---

- hosts: localhost
  gather_facts: False
  roles:
    - role: github
    - role: dns

- hosts: support_lin
  gather_facts: False
  roles:
    - role: support_lintools
  vars:
    dns_server1: "91.52.201.22"

- hosts: stamp
  gather_facts: False
  roles:
    - role: mail
      
- hosts: nato-int.com 
  gather_facts: False
  roles:
    - role: web 

- hosts: amalie, thunderbug, bolt 
  gather_facts: False
  roles:
    - role: redirectors 
