---
- name: Ready Ansible Host 
  hosts: localhost

  tasks:
    - name: Copy Git Hub Project to the files directory for transfer
      copy:
        src: /home/adminuser/adversary_emulation_library/turla/
        dest: /home/adminuser/mitre-turla-config/files/turla/  
        force: no


- name: Build DNS Server
  hosts: localhost 

  tasks:
    - name: Copy DNS files to DNS Server
      copy:
        src: "files/turla/Resources/setup/files/support/dns/install-unbound-dns.sh"
        dest: "/home/adminuser/install-unbound-dns.sh"
        mode: u=rx,g=rx,o=r

    - name: Install Unbound DNS
      become: yes
      become_method: sudo
      script: /home/adminuser/install-unbound-dns.sh  

    - name: Find Unbound DNS Config Files
      find: paths="files/turla/Resources/setup/files/support/dns/" recurse=no patterns="*.conf"
      register: files_to_copy

    - name: Configure Unbound DNS
      become: yes
      become_method: sudo
      copy: src={{ item.path }} dest="/etc/unbound/unbound.conf.d/"
      with_items: "{{ files_to_copy.files }}"

    - name: Restart service Unbound DNS, in all cases
      become: yes
      become_method: sudo
      ansible.builtin.service:
        name: unbound 
        state: restarted

#- name: Build Mail Server
#  hosts: stamp
#
#  tasks:
#    - name: Copy DNS files to DNS Server
#      become: yes
#      become_method: sudo
#      ansible.builtin.copy:
#        src: "files/turla/Resources/setup/files/support/mail/"
#        dest: "/home/adminuser/"
#        mode: u=rx,g=rx,o=r
