---
- name: Ready Ansible Host 
  hosts: localhost

  tasks:
    - name: Copy Git Hub Project to the files directory for tansfer
      copy:
        src: /home/adminuser/adversary_emulation_library/turla/
        dest: /home/adminuser/mitre-turla-config/files/turla/  
        force: no
