---
- name: Download and Deploy Cortex XSIAM Agent on Windows
  hosts: carbon_win
  tasks:

    - name: Download Cortex XSIAM Agent to Ansible Control Node
      local_action:
        module: uri
        url: "{{ xsiam_api_url }}/public_api/v1/distributions/get_dist_url"
        method: POST
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
          Authorization: "{{ xsiam_api_key }}"
          x-xdr-auth-id: "{{ xsiam_api_id }}"
        body_format: json
        body:
          {
            request_data: {
            distribution_id: "{{ distribution_id }}",
            package_type: "x64"
            }
          }
        return_content: yes
        timeout: 60
      run_once: true 
      register: response

    - name: Extract the download URL
      set_fact:
        download_url: "{{ response.json.reply.distribution_url }}"

    - name: Make Ansible Files Directory if it doesn't exist
      delegate_to: localhost
      file:
        path: "./files"
        state: directory
        mode: '0755'
      run_once: true

    - name: Download Cortex XSIAM Agent Installer {{ download_url }}
      local_action:
        module: uri
        url: "{{ download_url }}"
        method: POST 
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
          Authorization: "{{ xsiam_api_key }}"
          x-xdr-auth-id: "{{ xsiam_api_id }}"
        dest: "./files/cortex_xsiam_agent.msi"
        timeout: 60
        mode: '0644'
      run_once: true 

    - name: Copy the agent installer to the remote Windows host
      win_copy:
        src: "./files/cortex_xsiam_agent.msi"
        dest: "C:\\Windows\\Temp\\cortex_xsiam_agent.msi"

    - name: Install Cortex XSIAM Agent silently
      win_shell: |
        msiexec /i C:\Windows\Temp\cortex_xsiam_agent.msi /quiet /norestart
      args:
        executable: cmd

    - name: Wait for Cortex XSIAM service to start
      when: ansible_os_family == "Windows"
      win_wait_for:
        port: 3389
        timeout: 120
        ignore_errors: yes

    - name: Wait for Cortex XSIAM service to start
      when: ansible_os_family in ["RedHat", "Debian","Ubuntu"]
      win_wait_for:
        port: 22
        timeout: 120
        ignore_errors: yes

    - name: Check Cortex XDR on Windows
      when: ansible_os_family == "Windows"
      block:
        - name: Run cytool checkin on Windows
          ansible.windows.win_shell: "& 'C:\\Program Files\\Palo Alto Networks\\Traps\\cytool.exe' checkin"
          register: cytool_result
          ignore_errors: yes

        - name: Debug Windows XDR installed
          debug:
            msg: "Cortex XDR is installed on Windows"
          when: cytool_result.stdout == ""

        - name: Debug Windows XDR missing
          debug:
            msg: "Cortex XDR is NOT installed on Windows"
          when: cytool_result.rc != 0

    - name: Check Cortex XDR on Linux
      when: ansible_os_family in ["RedHat", "Debian","Ubuntu"]
      block:
        - name: Run cytool checkin on Linux
          shell: '/opt/traps/bin/cytool checkin'
          register: cytool_result
          ignore_errors: yes

        - name: Debug Linux XDR installed
          debug:
            msg: "Cortex XDR is installed on Linux"
          when: cytool_result.stdout == ""

        - name: Debug Linux XDR missing
          debug:
            msg: "Cortex XDR is NOT installed on Linux"
          when: cytool_result.rc != 0


