---

  - name: Remove specified repository from sources list.
    become: yes
    become_method: sudo
    apt_repository:
      repo: deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
      state: absent
    when: (ansible_facts['distribution'] == "Kali")

  - name: Add source repository into sources list.
    become: yes
    become_method: sudo
    apt_repository:
      repo: deb http://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling main non-free contrib non-free-firmware
      state: present
    when: (ansible_facts['distribution'] == "Kali")

  - name: Remove specified repository from sources list Kali.
    apt_repository:
       repo: deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
       state: absent
    when: (ansible_facts['distribution'] == "Kali")

  - name: Add source repository into sources list on Kali.
    apt_repository:
       repo: deb http://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling main non-free contrib non-free-firmware
       state: present
    when: (ansible_facts['distribution'] == "Kali")

  - name: Install Resolv.conf
    become: yes
    become_method: sudo
    ansible.builtin.command: "apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages systemd-resolved"
    register: resolvconf_installed

  - name: Remove DNS server entry 8.8.8.8
    become: yes
    become_method: sudo
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: "nameserver 8.8.8.8"
      state: absent

  - name: Remove DNS server entry 8.8.8.8
    become: yes
    become_method: sudo
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: "nameserver 127.0.0.53"
      state: absent

  - name: Configure DNS servers
    become: yes
    become_method: sudo
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: "{{ item }}"
      state: present
      insertafter: BOF
    with_items: "{{ dns_servers }}"    
    
  - name: Update Apt repo and cache
    become: yes
    become_method: sudo
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Set timezone to Etc/UTC 
    become: yes
    become_method: sudo
    community.general.timezone:
      name: Etc/UTC
      
  - name: Install NTPSec
    become: yes
    become_method: sudo
    ansible.builtin.apt:
      force: true
      name: ntpsec
    register: ntpsec_installed
      
  - name: Install NTP
    become: yes
    become_method: sudo
    ansible.builtin.apt:
      name: ntp
    register: ntp_installed
   
  - name: Restart service NTP, in all cases
    become: yes
    become_method: sudo
    ansible.builtin.service:
      name: ntpsec 
      state: restarted 
    when: ntp_installed is changed 

  - name: Set HostName 
    become: yes
    become_method: sudo
    ansible.builtin.lineinfile:
      path: /etc/hosts 
      regexp: '^127\.0\.0\.1 localhost\s*$'
      line: 127.0.0.1 localhost {{ inventory_hostname }}
      owner: root
      group: root
      mode: '0644'

  - name: Set Hostname
    become: yes
    become_method: sudo
    hostname:
      name: "{{ inventory_hostname }}"
