---

- name: Ansible check ViperVPN Installer exists.
  win_stat: 
    path: C:\Windows\Temp\ViperVPN.exe
  register: vipervpn_installer 

- name: Copy Viper VPN Build Files
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/windows-service/ 
    dest: C:\Users\{{ ansible_user }}\
  when: vipervpn_installer.stat.exists == False

- name: Install Python and Build Viper VPN if needed 
  include_tasks: viperVPN.yml
  when: vipervpn_installer.stat.exists == False


