---

- name: Ansible check DNS file exists.
  ansible.windows.win_stat:
    path: C:\Windows\Temp\bannik-set-dns-resolution.ps1
  register: dns_file

- name: Ansible WebServer Group file exists.
  ansible.windows.win_stat:
    path: C:\Windows\Temp\bannik-set-adalwolfa-group-membership.ps1
  register: webserver_group 

- name: Ansible Computer Descriptions file exists.
  ansible.windows.win_stat:
    path: C:\Windows\Temp\bannik-add-computer-descriptions.ps1
  register: computer_descriptions 

- name: Copy Carbon DNS Configuration bannik-set-dns-resolution.ps1
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/bannik-set-dns-resolution.ps1
    dest: C:\Windows\Temp\bannik-set-dns-resolution.ps1
  when: dns_file.stat.exists == False
 
- name: Copy Group Membership for Websevers Configuration bannik-set-adalwolfa-group-membership.ps1
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/bannik-set-adalwolfa-group-membership.ps1
    dest: C:\Windows\Temp\bannik-set-adalwolfa-group-membership.ps1
  when: webserver_group.stat.exists == False
 
- name: Copy Computer Descriptions config bannik-add-computer-descriptions.ps1 
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/bannik-add-computer-descriptions.ps1
    dest: C:\Windows\Temp\bannik-add-computer-descriptions.ps1
  when: computer_descriptions.stat.exists == False
 
- name: Add Computer Descriptions 
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-add-computer-descriptions.ps1
  when: computer_descriptions.stat.exists == False

- name: Add Kagarov to Group for WebServers 
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-set-adalwolfa-group-membership.ps1
  when: webserver_group.stat.exists == False

- name: Configure DNS
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-set-dns-resolution.ps1
  when: dns_file.stat.exists == False
