---

- name: Update Apt repo and cache
  become: yes
  become_method: sudo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  

#- name: Copy DNS files to DNS Server
#  become: yes
#  become_method: sudo
#  ansible.builtin.copy:
#    src: "files/turla/Resources/setup/files/support/mail/"
#    dest: "/home/adminuser/"
#    mode: u=rx,g=rx,o=r
