---

- name: Update Apt repo and cache
  become: yes
  become_method: sudo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install the package "Postfix Server"
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name: 
      - mailutils
      - postfix 
      - ripmime 
      - procmail 
  
- name: Edit Domains in resolved.conf (recreation of stamp-configure-dns.sh) 
  become: yes
  become_method: sudo
  shell: sed -i 's/#Domains=/Domains=skt.local nk.local/g' /etc/systemd/resolved.conf

- name: Restart service Resolved Service (recreation of stamp-configure-dns.sh)
  become: yes
  become_method: sudo
  ansible.builtin.service:
    name: systemd-resolved 
    state: restarted

- name: Copy Mail Server Name File to Mail Server
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/turla/Resources/setup/files/support/mail/etc_mailname"
    dest: "/etc/mailname"

- name: Copy Mail Server Main File to Mail Server
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/turla/Resources/setup/files/support/mail/etc_postfix_main.cf"
    dest: "/etc/postfix/main.cf"

- name: Copy Mail Server Virtual File to Mail Server
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/turla/Resources/setup/files/support/mail/etc_postfix_virtual"
    dest: "/etc/postfix/virtual"

- name: Build Virtual Domain Aliases 
  become: yes
  become_method: sudo
  shell: postmap /etc/postfix/virtual 

- name: Replace name server line
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver 127.0.0.53'
    line: 'nameserver 91.52.201.22'
    state: present

- name: Enable service PostFix, and not touch the state
  ansible.builtin.service:
    name: postfix 
    enabled: yes

- name: Restart service Postfix Service 
  become: yes
  become_method: sudo
  ansible.builtin.service:
    name: postfix 
    state: restarted
