---

#- name: Update Apt repo and cache
#  become: yes
#  become_method: sudo
#  ansible.builtin.apt:
#    name: "*"
#    state: latest

#- name: Update Archive Keyring
#  become: yes
#  become_method: sudo
#  ansible.builtin.apt_key:
#    url: https://archive.kali.org/archive-key.asc 
#    state: present

#- name: Update Apt repo and cache
#  become: yes
#  become_method: sudo
#  ansible.builtin.apt:
#    name: "*"
#    state: latest

#- name: Check For Reboot Required 
#  include_tasks: reboot.yml

#- name: Upgrade Kali
#  become: yes
#  become_method: sudo
#  ansible.builtin.apt:
#    upgrade: full 
#    dpkg_options: 'force-confold,force-confdef'

#- name: Check For Reboot Required 
#  include_tasks: reboot.yml

#- name: Upgrade Release 
#  become: yes
#  become_method: sudo
#  ignore_errors: true
#  shell: do-release-upgrade -f DistUpgradeViewNonInteractive 

#- name: Check For Reboot Required 
#  include_tasks: reboot.yml

#- name: Install the Prerequisite packages
#  become: yes
#  become_method: sudo
#  ansible.builtin.apt:
#    name:
#    - xfce4 

#- name: Check For Reboot Required
#  include_tasks: reboot.yml

- name: Make Day1, Day2, and watering_hole folders
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /opt/{{ item }}
    state: directory
  with_items:
  - day1
  - day2
  - watering_hole

- name: Install the Prerequisite packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
    - apache2
    - default-mysql-server
    - golang
    - xdotool
    - python3-urllib3
    - ncat
    - python3-pip
    - xorg
    - xrdp
- name: Install the Prerequisite packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
    - augeas-tools
    - augeas-lenses
    - git
    - etckeeper
    - postfix
    - ripmime
    - mailutils
    - procmail
    - swaks
    - php
    - php-mysql
    - ruby
    - ruby-dev
    - make
    - mariadb-client
    - mariadb-server

- name: Ensure Apache2 is enabled and running
  become: yes
  become_method: sudo
  service:
    name: apache2
    enabled: true
    state: started

- name: Check For Reboot Required 
  include_tasks: reboot.yml

- name: Auto Remove Old Packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    autoremove: true 

- name: Create Cradwell User
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name: cradwell

#- name: Turn Off Screen Saver Lock 
#  become: yes
#  become_method: sudo
#  ignore_errors: true
#  shell: xset s off; sleep 1; xset s noblank 

