---

###  Add Kali Repos 
- name: Add Kali Repo to Apt Source List
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: deb http://http.kali.org/kali kali-rolling main non-free non-free-firmware
    create: yes

- name: Add Kali Repo Source to Apt Source List
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: deb-src http://http.kali.org/kali kali-rolling main non-free non-free-firmware
    create: yes

- name: Add Kali Key to Repo Recieve Key
  become: yes
  become_method: sudo
  shell: gpg --keyserver keyserver.ubuntu.com --recv-key 7D8D0BF6

- name: Add Kali Key to Repo Add Key
  become: yes
  become_method: sudo
  shell: gpg -a --export 7D8D0BF6 | sudo apt-key add -

- name: Update Apt repo and cache
  become: yes
  become_method: sudo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Make Day1, Day2, and watering_hole folders
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /opt/{{ item }}
    state: directory
  with_items:
  - day1
  - day2
  - watering_hole

- name: Update Apt repo and cache
  become: yes
  become_method: sudo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Check For Reboot Required 
  include_tasks: reboot.yml

- name: Install the Prerequisite packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
    - golang
    - xdotool
    - python3-urllib3
    - ncat
    - python3-pip
    - kali-desktop-xfce
    - xorg
    - xrdp
    - augeas-tools
    - augeas-lenses
    - git
    - etckeeper
    - postfix
    - ripmime
    - mailutils
    - procmail
    - swaks
    - php
    - php-mysql
    - ruby
    - default-mysql-server
    - mariadb-client
    - mariadb-server
    - apache2
    state: build-dep

- name: Check For Reboot Required 
  include_tasks: reboot.yml

- name: Create Cradwell User
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name: cradwell
