---

- name: Check if a reboot is required
  become: yes
  become_method: sudo
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  become: yes
  become_method: sudo
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
