---

- name: Check if Machine is Domain Joined 
  win_shell: systeminfo | findstr /i "domain" 
  register: domain_results

- name: Copy Domain Users RDP 
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/all-carbon-enable-remote-desktop-for-domain-users.ps1  
    dest: C:\Windows\Temp\all-carbon-enable-remote-desktop-for-domain-users.ps1
 
- name: Set a single address on the adapter named Ethernet
  win_dns_client:
    adapter_names: '*' 
    ipv4_addresses: 10.20.10.9

- name: Set DNS suffix 
  win_command: powershell.exe Set-DnsClientGlobalSetting -SuffixSearchList @("skt.local") 

- name: Allow Storing of wdigest credentials
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest
    name: UseLogonCredential 
    type: dword
    data: 1 

- name: Configure firewall to allow smb 
  win_command: powershell.exe Enable-NetFirewallRule -DisplayGroup 'File and Printer Sharing' 

- name: Configure firewall to allow schtasks 
  win_command: powershell.exe Enable-NetFirewallRule -DisplayGroup 'Remote Scheduled Tasks Management' 

- name: Join Domain 
  ansible.windows.win_powershell:
    script: |
          $username = "evals_domain_admin"
          $DomainName = "skt"
          $SecPassword = "DuapQj7k8Va8U1X27rw6" | ConvertTo-SecureString -AsPlainText -Force
          $DomainCred = New-Object System.Management.Automation.PSCredential ("$DomainName\$($username)", $SecPassword)
          Add-Computer -DomainName "SKT.local" -Credential $DomainCred -Force

#- name: Sleep for 60 seconds and continue with play
#  ansible.builtin.wait_for:
#    timeout: 60
#  delegate_to: localhost

- name: Enable Domain Users RDP
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\all-carbon-enable-remote-desktop-for-domain-users.ps1 
