---

- name: Ansible check Domain Users file exists.
  ansible.windows.win_stat:
    path: C:\Windows\Temp\bannik-create-carbon-users.ps1
  register: domain_users

- name: Copy Carbon Domain Groups and User Configuration bannik-create-carbon-users.ps1
  ansible.windows.win_copy:
    src: files/carbon/bannik-create-carbon-users.ps1
    dest: C:\Windows\Temp\bannik-create-carbon-users.ps1
  when: domain_users.stat.exists == False

- name: Create new Windows domain in a new forest with specific parameters
  ansible.windows.win_domain:
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    dns_domain_name: skt.local
    domain_mode: WinThreshold 
    domain_netbios_name: SKT
    forest_mode: WinThreshold 
    safe_mode_password: j4yqN3EYcL_KQ?L2
    log_path: C:\Windows\NTDS
    sysvol_path: C:\Windows\SYSVOL
  register: domain_install

- name: (reboot) Wait for server to restart
  ansible.windows.win_reboot:
    reboot_timeout: 3600
  ignore_errors: true
  when: domain_install.reboot_required 

- name: Check if Machine is Domain Joined
  win_shell: systeminfo | findstr /i "domain"
  register: dc_results

- name: Configure Domain Groups and Users 
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-create-carbon-users.ps1
  when: "'Primary Domain Controller' in dc_results.stdout"

