---

- name: Ansible check Domain Config file exists.
  win_stat: 
    path: C:\Windows\Temp\bannik-create-carbon-domain.ps1
  register: domain_config 

- name: Ansible check Domain Users file exists.
  ansible.windows.win_stat:
    path: C:\Windows\Temp\bannik-create-carbon-users.ps1
  register: domain_users

- name: Copy Domain Configuration Script bannik-create-carbon-domain.ps1
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/bannik-create-carbon-domain.ps1
    dest: C:\Windows\Temp\bannik-create-carbon-domain.ps1
  when: domain_config.stat.exists == False

- name: Copy Carbon Domain Groups and User Configuration bannik-create-carbon-users.ps1
  ansible.windows.win_copy:
    src: files/carbon/bannik-create-carbon-users.ps1
    dest: C:\Windows\Temp\bannik-create-carbon-users.ps1
  when: domain_users.stat.exists == False

- name: Set Domain 
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-create-carbon-domain.ps1
  ignore_errors: true
  when: domain_config.stat.exists == False

- name: (reboot) Wait for server to restart
  ansible.windows.win_reboot:
    reboot_timeout: 3600
  when: domain_config.stat.exists == False

- name: Check if Machine is Domain Joined
  win_shell: systeminfo | findstr /i "domain"
  register: dc_results

- name: Configure Domain Groups and Users 
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\bannik-create-carbon-users.ps1
  when: "'Primary Domain Controller' in dc_results.stdout"

