---

- name: Check Install Exchange script exists
  win_stat:
    path: C:\Windows\Temp\brieftragerin-install-exchange.ps1
  register: exchange_installer

- name: Check Exchange ISO 
  win_stat:
    path: C:\Windows\Temp\EXCHANGE2019.ISO 
  register: exchange_iso

- name: Copy Exchange Install Script 
  ansible.windows.win_copy:
    src: files/carbon/brieftragerin-install-exchange.ps1
    dest: C:\Windows\Temp\brieftragerin-install-exchange.ps1
  when: exchange_installer.stat.exists == False

- name: Download Exchange ISO
  win_get_url:
    url: https://download.microsoft.com/download/b/c/7/bc766694-8398-4258-8e1e-ce4ddb9b3f7d/ExchangeServer2019-x64-CU12.ISO
    dest: C:\Windows\Temp\EXCHANGE2019.ISO
  when: exchange_iso.stat.exists == False


- name: set baseline Windows features to install
  set_fact:
    pri_exchange_features:
      - NET-WCF-HTTP-Activation45
      - RPC-over-HTTP-proxy
      - RSAT-ADDS
      - RSAT-ADDS-Tools
      - RSAT-Clustering
      - RSAT-Clustering-CmdInterface
      - RSAT-Clustering-Mgmt
      - RSAT-Clustering-PowerShell
      - Web-ASP-NET45
      - Web-Digest-Auth
      - Web-Dyn-Compression
      - Web-ISAPI-Ext
      - Web-Mgmt-Console
      - Web-Mgmt-Service
      - Web-Net-Ext45
      - Web-WMI

- name: ensure Windows features are present
  win_feature:
    name: '{{ pri_exchange_features }}'
    state: present
  register: pri_exchange_feature_install

- name: reboot after installing Windows features
  win_reboot:
  when: pri_exchange_feature_install.reboot_required
              
- block:
  - name: install .NET 4.8 and Visual C++ 2013 redistributable
    win_chocolatey:
      name:
      - netfx-4.8
      - vcredist2013
      state: present
    register: pri_exchange_choco_install

  - name: reboot after installing .NET 4.8 and Visual C++ 2013 redistributable
    win_reboot:
    when: pri_exchange_choco_install is changed

- name: install URL IIS Rewrite Module
  win_chocolatey:
    name: 
    - urlrewrite
    state: present

- name: install Unified Communications Managed API 4.0 Runtime
  win_package:
    path: https://download.microsoft.com/download/2/C/4/2C47A5C1-A1F3-4843-B9FE-84C0032C61EC/UcmaRuntimeSetup.exe
    arguments: /q /norestart
    product_id: UCMA4
    state: present
  register: pri_exchange_ucma_install

- name: reboot after installing Unified Communications Managed API 4.0 Runtime
  win_reboot:
  when: pri_exchange_ucma_install.reboot_required

- name: Ensure the Exchange ISO is mounted
  become: yes
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
  community.windows.win_disk_image:
    image_path: C:\Windows\Temp\EXCHANGE2019.ISO 
    state: present
  register: disk_image_out

- name: Prepare AD from {{ disk_image_out.mount_paths[0] }}Setup.EXE
  win_package:
    path: '{{ disk_image_out.mount_paths[0] }}Setup.EXE'
    arguments: >-
      /IAcceptExchangeServerLicenseTerms_DiagnosticDataOFF
      /PrepareAD
      /OrganizationName:"skt"
    product_id: '{CD981244-E9B8-405A-9026-6AEB9DCEF1F1}' 
    state: present
  become: yes 
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
    
- name: Install Exchange from {{ disk_image_out.mount_paths[0] }}Setup.EXE
  win_package:
    path: '{{ disk_image_out.mount_paths[0] }}Setup.EXE'
    arguments: >-
      /IAcceptExchangeServerLicenseTerms_DiagnosticDataOFF
      /mode:Install
      /role:Mailbox
      /OrganizationName:"skt"
      /InstallWindowsComponents
      /DisableAMFiltering
    product_id: '{CD981244-E9B8-405A-9026-6AEB9DCEF1F1}' 
    state: present
  register: pri_exchange_install
  become: yes 
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
    
- name: Reboot Exchange Server
  ansible.windows.win_reboot:
    reboot_timeout: 3600
  when: pri_exchange_install is changed

- name: Check Create Exchange Admin script exists
  win_stat:
    path: C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
  register: exchange_admin

- name: Copy Create Exchange Admin Script 
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/brieftragerin-create-carbon-exchange-admin.ps1
    dest: C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
  when: exchange_admin.stat.exists == False

- name: Create Exchange Admin
  become: yes
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
#
