---

- name: Check Install Exchange script exists
  win_stat:
    path: C:\Windows\Temp\brieftragerin-install-exchange.ps1
  register: exchange_installer

- name: Check Exchange ISO 
  win_stat:
    path: C:\Windows\Temp\EXCHANGE2019.ISO 
  register: exchange_iso

- name: Copy Exchange Install Script 
  ansible.windows.win_copy:
    src: files/carbon/brieftragerin-install-exchange.ps1
    dest: C:\Windows\Temp\brieftragerin-install-exchange.ps1
  when: exchange_installer.stat.exists == False

- name: Download Exchange ISO
  win_get_url:
    url: https://download.microsoft.com/download/b/c/7/bc766694-8398-4258-8e1e-ce4ddb9b3f7d/ExchangeServer2019-x64-CU12.ISO
    dest: C:\Windows\Temp\EXCHANGE2019.ISO
  when: exchange_iso.stat.exists == False

- name: Install Exchange  
  become: yes
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\brieftragerin-install-exchange.ps1
  when: exchange_installer.stat.exists 

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.windows.win_reboot:
    reboot_timeout: 3600
  when: exchange_installer.stat.exists == False

- name: Sleep for 60 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 60
  delegate_to: localhost
  when: exchange_installer.stat.exists == False

- name: Check Create Exchange Admin script exists
  win_stat:
    path: C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
  register: exchange_admin
  when: exchange_installer.stat.exists == False

- name: Copy Create Exchange Admin Script 
  ansible.windows.win_copy:
    src: files/turla/Resources/setup/files/carbon/brieftragerin-create-carbon-exchange-admin.ps1
    dest: C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
  when: exchange_admin.stat.exists == False

- name: Create Exchange Admin
  become: yes
  become_method: runas
  vars:
    ansible_become_user: 'skt\evals_domain_admin'
    ansible_become_pass: 'DuapQj7k8Va8U1X27rw6'
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\brieftragerin-create-carbon-exchange-admin.ps1
  when: exchange_admin.stat.exists

